### ISSUE TITLE
setup.py problem (Python 3.5)

### ISSUE THREAD

**Issue by Twangist** [alex-sherman/deco#13]
I downloaded the archive and thought I would install from the directory containing setup, in a Py3.5 virtual env. Just trying the`--help` option gives:

    $ ./setup.py --help
    from: can't read /var/mail/distutils.core
    ./setup.py: line 3: syntax error near unexpected token `newline'
    ./setup.py: line 3: `setup('

`pip install deco` works just fine, so this is a minor issue. However, the PyPI version of deco seems to be not up to date.

**Comment by alex-sherman** [comment]
I'll change setup.py to be executable with bash, it's probably more intuitive that way.

That error can be avoided, however, by calling `python setup.py install` instead. This happens because bash is trying to interpret the python script.

Thanks for pointing this out!
