### ISSUE TITLE
Version on PyPI seems not to import conc correcly

### ISSUE THREAD

**Issue by luiscape** [alex-sherman/deco#14]
When installing the version available on PyPI the statement `import conc` on `deco/__init__.py` does not import `deco.py` correctly, eventually failing on usage. The master version seems to have corrected that issue.

It may be worth making a new release with this issue fixed.

**Comment by alex-sherman** [comment]
Thanks for pointing that out, I've created a new release. Let me know if you still have problems with the PyPI version.
