### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by benmoran56** [alex-sherman/deco#2]
Hi, just wondering if you plan to update this to work on Python 3?

**Comment by alex-sherman** [comment]
Do the actual decorators not work in Python 3? I would be surprised if they didn't, but can't say for sure since. If you're referring to the old style print statements in the examples, I can definitely update those at some point, but probably the main module should work as is in Python 3.

**Comment by benmoran56** [comment]
Hi Alex, thanks for the reply. Yes, there are some issues with decorators in Python 3. The problem is that the ast module has changed a little bit between versions, so there is no longer an "id" attribute for the nodes.  Here is another project that has a dual Py2/3 compatible workaround for this issue: 
https://github.com/jck/myhdl/commit/9cb4b23ef9b0b7b8798cff12ca6b1af317530a2f

There are also other minor issues, such as the imports in your __init__.py, and the exec statement being a function now. I made a tiny pull request that sorts out the __init__.py file, but didn't want to include any changes to deco.py for now.

**Comment by alex-sherman** [comment]
Thanks very much for the pull request and the info on the changes to the AST. I'll look into that further and see what I can do to provide 2/3 compatibility.

**Comment by alex-sherman** [comment]
I was able to get the climate_model example working in Python 3.5 with 9da30aaaf963cb6d2e85627b03a5fc9af16889e3.

Function arguments in Python 3.5 were still Names with an `id` attribute though. If you're still having that problem could you let me know which Python version you're using exactly?

**Comment by benmoran56** [comment]
The climage model works fine for me! Thanks a lot for updating this. I guess you can disregard my comments about the *id* attribute. I'm not very familiar with the *AST* module myself, so I was just basing it on what I read elsewhere. 

I'll see if I can put *deco* through it's paces when I have some free time, and I'll be sure to open a fresh ticket if I see any issues.
