### ISSUE TITLE
@synchronized with generators

### ISSUE THREAD

**Issue by saethlin** [alex-sherman/deco#21]
Because of the index-based limitation, this is currently not supported:
```
@synchronized
for thing in range(10):
    concurrent_function(thing)
```
Obviously there's a simple workaround in most cases to just use `list(generator)`. Do you plan to support generators in the future or is this a race condition problem?

**Comment by alex-sherman** [comment]
The example you have is definitely allowed by deco, the index-based limitation applies to objects that get mutated by the concurrent function. Because Python already doesn't let you mutate numbers, we don't have to worry about them.

I might have mis-interpreted your example though, are you talking about passing a generator to the concurrent_function?

**Comment by saethlin** [comment]
Strange. I must have mis-interpreted what was going on. The example below does not work, can you tell me why?
```
import time
from deco import concurrent, synchronized

@concurrent
def slow(index):
    time.sleep(index)

@synchronized
def run():
    for i in range(5):
        slow(4)

if __name__ == '__main__':
    run()
```

**Comment by alex-sherman** [comment]
Oh good catch! This is actually a bug slightly related to another issue we have open. I very much need to improve the way deco handles concurrent function arguments. What's happening is that it's looking for the names of all the arguments to `slow`, expecting them to all be names or indexed accesses to names. I'll leave this open to make sure the fixes I make for the other issue also address this.

Thanks for pointing it out!

**Comment by alex-sherman** [comment]
I got this specific example to work with 79fe24c9b5f0c30d1ea2db4ce418ed20a00a3385. I'm going to close this for now, but let me know if this is still not working.

Thanks again!
