### ISSUE TITLE
Example of a dynamic work load.

### ISSUE THREAD

**Issue by rseward** [alex-sherman/deco#23]
Is it possible to have your concurrent function accept new work items after the concurrent function has been started already? Perhaps with a work queue for instance?

I gather from the documentation and examples this is not possible at this time.

Nice work on a clean , simple way of enabling multiprocessing in a straight forward way!

Thank you,
Rob

**Comment by alex-sherman** [comment]
It's definitely possible! The concurrent function already acts as sort of a work queue, each time it's called it's sort of like an item being added to the work queue. This queue does get periodically cleared when a synchronization event occurs, but as long as there is no synchronization every new call to concurrent functions gets sort of pushed into the work queue even after the work has been started.

Thanks for the question! Feel free to follow up if this wasn't clear or I misunderstood what you were asking.

**Comment by rseward** [comment]
Are there any examples of adding work for the threads while they are executing?

**Comment by alex-sherman** [comment]
I would say that in a way all the examples we have are examples of adding work while the processes/threads are executing, but it's sort of a perspective thing. The first time a concurrent function is called the processes/threads get created and begin executing and that first work item is added to the queue. Every concurrent function call from then on out is like adding work to these processes/threads until they ultimately get joined during a synchronization event.

If I'm still maybe misunderstanding your question, could you maybe provide like a pseudo code example of what you're describing?
