### ISSUE TITLE
Synchronized concurrent method?

### ISSUE THREAD

**Issue by aliabbasjp** [alex-sherman/deco#27]
```
@concurrent
def preprocess(txt):
    txt = rep.replace(txt)
    txt = txt.split(u'\n')
    return txt


@concurrent
@synchronized
def readfile(path):
    txt= codecs.open(path, encoding='utf-8').read().strip()
    return preprocess(txt)
```

In the above code I want preprocess to be called individually hence even that is marked as concurrent and since I am using it in readfile I have marked it as both 
@concurrent
@synchronized

However error thrown :TypeError: unsupported operand type(s) for -: 'synchronized' and 'int'

**Comment by alex-sherman** [comment]
I had never thought of trying this, that's awesome! I'll have to make sure to add this to some documentation somewhere, but the short answer is you can't use `@concurrent` decorators on `@synchronized` functions.

The longer answer is that it might be possible, but I don't think deco will be able to support it and I suspect that any case where this could have been used can be converted to an equivalent program that doesn't require the double decorators. The main reason this is hard to support is that deco assumes that synchronization events happen in the main process, where it can operate access the original objects and not copies or proxies. It's possible that even if synchronization events operated on proxy objects in another concurrent function that everything would still work out correctly once that function gets synchronized but I'm not actually sure. This is definitely an interesting thought that we might revisit in the future, but for now I'm going to avoid this sort of concurrency inception.

Thanks for bringing this up!
