### ISSUE TITLE
Python 3.5: dict object no method 'itermitems'

### ISSUE THREAD

**Issue by jkaan** [alex-sherman/deco#29]
I'm not exactly sure if this is a problem on my end or with this library, but I can't seem to find the solution.

**Comment by re4lfl0w** [comment]
Same problem to me.

**Comment by alex-sherman** [comment]
Thanks for catching this! I should start running tests for Python 3 as well before pushing stuff. I've pushed a solution that I think should work in 05756726d76543233471384df1fc4394ab545575.

If that works for you feel free to close this, thanks again for pointing this out.

**Comment by re4lfl0w** [comment]
@alex-sherman I think fixed code is working in python3 well but didn't work in python2. that's ok?

**Comment by alex-sherman** [comment]
Could you elaborate on what's not working in Python 2? The tests and examples I have all still work in Python 2. If possible, could you provide a short code example that does not work in Python 2?
