### ISSUE TITLE
Processes don't exit upon completion

### ISSUE THREAD

**Issue by dustyny** [alex-sherman/deco#43]
I'm using deco with Ubuntu 16 and Python 3. When I run my script, I can successfully spin up 6 processes but they don't exit when the script is finished running. Next time I run it, it spins up another 6 processes. So in this example, I'll have 12+ instance of python running. 

Is there a way to gracefully shut them down that I'm missing?

**Comment by alex-sherman** [comment]
Can you post a script that causes this issue? I believe that Python multiprocessing `Pool` creates child processes that are daemons so that when the main process exits, all the children are terminated as well. Another thing you might check is whether or not the main process is actually exiting.

**Comment by dustyny** [comment]
It's probably how I'm using it. I'm very new to python and multiprocessing. I forgot to mentions that I'm running it in a Jupyter notebook, if that makes any difference. 



`@concurrent
def get_url(start_num):
    global counter
    # query lucidworks to get the article document

    querystring = {"wt":"json","start":start_num,"q":"%2A%3A%2A","rows":"1"}
    response = requests.request("GET", url, headers=headers, params=querystring)
    
    if response.status_code == 200:        
        # save the response into a json object for processing
        response_json = response.json()      
        
              
        # create the article file name        
        article_url = response_json['response']['docs'][0]['url'][0]
        article_url = urlparse(article_url)
        article_url_path = article_url.path.split('/')
        article_filename = article_url_path[-2]
        
        # extract the domain name with no tld extension and save it to use in the file name. 
        pub_domain_name = article_url.netloc
        pub_domain_name = pub_domain_name.split('.')
        pub_domain_name = pub_domain_name[0]
        
        # set the filename & directory to save it to
        html_filename_with_dir = html_file_dir + pub_domain_name + '--' + article_filename.lower() + '.html'
        json_filename_with_dir = json_file_dir + pub_domain_name + '--' + article_filename.lower() + '.json'       
              
                
        #######
        #######  Need to check to see if the files exist already. If so skip processing
        #######
        html_check = os.path.isfile(html_filename_with_dir)        
        json_check = os.path.isfile(json_filename_with_dir)

        
        if html_check == True and json_check == True:
            json_size_check = os.stat(json_filename_with_dir).st_size
            html_size_check = os.stat(html_filename_with_dir).st_size          
                        
            if html_size_check != 0 and json_size_check != 0:
                pass
        else:            
            
            # convert raw encoded HTML to bytecode, then to string and write to HTML text file. 
            if '_raw_content_' in response_json['response']['docs'][0]:
                html_base64_encoded = response_json['response']['docs'][0]['_raw_content_']
                article_html_decoded = data = base64.b64decode(html_base64_encoded)                
                
                # write html file to disk
                def write_html_file(html_filename_with_dir):
                    try:
                        html_file = open(html_filename_with_dir, "w")
                        html_file.write(article_html_decoded.decode("utf-8"))
                        html_file.close()
                    except Exception:
                        logging.exception(pub_domain_name + '--' + article_filename.lower())
                    
                
                # !!! Need to check to see if file is there and if it is make sure it's not zero
                if os.path.isfile(html_filename_with_dir) == False:
                    write_html_file(html_filename_with_dir)
                elif html_check == 0:
                    write_html_file(html_filename_with_dir)
                else:
                    # file is there nothing to do
                    pass


                # clean up the JSON response and save to disk. 
                # this needs to be refactored in to a function
                response_json_no_raw = response_json['response']['docs'][0]
                if '_raw_content_' in response_json_no_raw:
                    del response_json_no_raw["_raw_content_"]
                if 'og_image_width' in response_json_no_raw:
                    del response_json_no_raw["og_image_width"]
                if '_lw_data_source_type_s' in response_json_no_raw:
                    del response_json_no_raw["_lw_data_source_type_s"]
                if 'xParsedBy_ss' in response_json_no_raw:
                    del response_json_no_raw["xParsedBy_ss"]
                if 'mimeType_s_txt' in response_json_no_raw:
                    del response_json_no_raw["mimeType_s_txt"]
                if '_lw_batch_id_s' in response_json_no_raw:
                    del response_json_no_raw["_lw_batch_id_s"]
                if 'parsing_s' in response_json_no_raw:
                    del response_json_no_raw["parsing_s"]
                if 'viewport' in response_json_no_raw:
                    del response_json_no_raw["viewport"]
                if 'msapplication_window' in response_json_no_raw:
                    del response_json_no_raw["msapplication_window"]
                if 'body_links_anchor_ss' in response_json_no_raw:
                    del response_json_no_raw["body_links_anchor_ss"]
                if 'body.links.type' in response_json_no_raw:
                    del response_json_no_raw["body.links.type"]
                if 'og_image_height' in response_json_no_raw:
                    del response_json_no_raw["og_image_height"]
                if 'title_lang' in response_json_no_raw:
                    del response_json_no_raw["title_lang"]
                if 'charSet_s' in response_json_no_raw:
                    del response_json_no_raw["charSet_s"]
                if 'mimeType_s' in response_json_no_raw:
                    del response_json_no_raw["mimeType_s"]
                if 'og_type' in response_json_no_raw:
                    del response_json_no_raw["og_type"]
                if 'msapplication_task' in response_json_no_raw:
                    del response_json_no_raw["msapplication_task"]
                if '_lw_data_source_pipeline_s' in response_json_no_raw:
                    del response_json_no_raw["_lw_data_source_pipeline_s"]
                if '_lw_data_source_pipeline_s' in response_json_no_raw:
                    del response_json_no_raw["_lw_data_source_pipeline_s"]
                if 'content_txt' in response_json_no_raw:
                    del response_json_no_raw["content_txt"]
                if '_version_' in response_json_no_raw:
                    del response_json_no_raw["_version_"]
               
            
                # write json file to disk
                def write_json_file(json_filename_with_dir):
                    try:
                        json_file = open(json_filename_with_dir, "w")
                        json_file.write(json.dumps(response_json_no_raw, indent=4, sort_keys=True))
                        json_file.close()
                    except Exception:
                        logging.exception(pub_domain_name + '--' + article_filename.lower())
            
            
                if os.path.isfile(json_filename_with_dir) == False:
                    write_json_file(json_filename_with_dir)
                elif os.path.isfile(json_filename_with_dir) == True:
                    if os.stat(json_filename_with_dir).st_size == 0:                        
                        write_json_file(json_filename_with_dir)
                else:
                    # file is there nothing to do
                    pass
        

@synchronized
def run(record_count):
    for index in range(record_count):
        get_url(index)

start = time()
record_count = 10000
run(record_count)
finish = time()
total_time = finish - start

print('run time: ', total_time)`

**Comment by alex-sherman** [comment]
Yeah it's a bit hard to debug since I can't execute the script directly and I've never used Jupyter. My hunch is that it has something to do with the different run-time environment. My first suggestion would be, since your workload is basically entirely IO bound, you might try using `concurrent.threaded` in place of the `concurrent` decorator. This will use threads instead of processes so hopefully your error will go away. My other suggestion would be to just run this code directly in a Python interpreter but I understand if that isn't possible.

If you're interested in debugging this further, can you verify in some way that the main process is actually exiting, like is the 'run time: x' part actually being printed?

**Comment by dustyny** [comment]
I'll give threading a try. Thanks for the insight. Really appreciate Deco it's a so much easier to work with.. 

BTW: I think you should consider a rename of the module. Deco is far to common of a word. It's very difficult to find any information on it via a search engine.

**Comment by dustyny** [comment]
Just wanted to confirm that it does have something to do with how Jupyter runs "cells" and keeps the process active.  If I use exit() to end the main process it does shutdown the subprocesses.
