### ISSUE TITLE
Getting concurrent results in dictionary

### ISSUE THREAD

**Issue by aliabbasjp** [alex-sherman/deco#45]
of late I am getting ConcurrentResult objects in my @synchronized methods , I have to explicity call <concurrentmethod>.wait() to wait for all the concurrent processed to finish.
Why is this happening?

**Comment by alex-sherman** [comment]
Can you post some source code?

**Comment by alex-sherman** [comment]
I believe I found the problem, I pushed a commit that fixes a bug that is at least similar to what you describe. The case it accounts for is when you try to read from a variable that is assigned to in a synchronized function, waits were previously not getting inserted properly before the access. I additionally fixed a bug in the test that would supposed to check for this. Please let me know if the current version in git fixes your problem and thanks so much for posting this issue, it was super useful!

**Comment by alex-sherman** [comment]
I'm pretty confident the bug fix I published should fix your problem. I published a new version on PyPi as well as pushing the changes in the repo. For now I'm going to close this issue, but if the new changes in fact did not fix your problem please let me know and I'll reopen this.
