### ISSUE TITLE
function(concurrent) in synchronized which is passed by value can not work

### ISSUE THREAD

**Issue by detectivebag** [alex-sherman/deco#48]
hi,

guys, thanks for your great lib. I read it from blog `https://www.peterbe.com/plog/deco`

I have a question on usage of synchronized, below code works fine. 
and I made small modification, it does not work now. 
The reason I am doing so is that I want to pass function to `run` as a parameter.
I am wondering if you could kindly explain why.
Thanks!

Working version:
```
import time, requests

urls = """
https://www.peterbe.com/plog/blogitem-040212-1
https://www.peterbe.com/plog/geopy-distance-calculation-pitfall
https://www.peterbe.com/plog/app-for-figuring-out-the-best-car-for-you
https://www.peterbe.com/plog/Mvbackupfiles
https://www.peterbe.com/plog/swedish-holidays-explaine
https://www.peterbe.com/plog/wing-ide-versus-jed
https://www.peterbe.com/plog/worst-flash-site-of-the-year-2010
""".strip().splitlines()

@concurrent
def download(url, data):
    t0 = time.time()
    assert requests.get(url).status_code == 200
    t1 = time.time()
    data[url] = t1-t0
  
@synchronized
def run(data):
    for url in urls:
        download(url, data)
    print(data)

t0 = time.time()
data = {}
run(data)
print(data)
t1 = time.time()
print ("TOOK", t1-t0)
print ("WOULD HAVE TAKEN", sum(data.values()), "seconds")
```

not working version:
```
import time, requests

urls = """
https://www.peterbe.com/plog/blogitem-040212-1
https://www.peterbe.com/plog/geopy-distance-calculation-pitfall
https://www.peterbe.com/plog/app-for-figuring-out-the-best-car-for-you
https://www.peterbe.com/plog/Mvbackupfiles
https://www.peterbe.com/plog/swedish-holidays-explaine
https://www.peterbe.com/plog/wing-ide-versus-jed
https://www.peterbe.com/plog/worst-flash-site-of-the-year-2010
""".strip().splitlines()

@concurrent
def download(url, data):
    t0 = time.time()
    assert requests.get(url).status_code == 200
    t1 = time.time()
    data[url] = t1-t0
  
function_map = {
    'download': download
}

@synchronized
def run(data):
    for url in urls:
        function_map['download'](url, data)
    print(data)

t0 = time.time()
data = {}
run(data)
print(data)
t1 = time.time()
print ("TOOK", t1-t0)
print ("WOULD HAVE TAKEN", sum(data.values()), "seconds")
```

**Comment by alex-sherman** [comment]
This is definitely an interesting case that I had not considered until now. I made a note of this under [Common Pitfalls](https://github.com/alex-sherman/deco/wiki/Common-Pitfalls) in the wiki just now.

What's happening is the `@synchronized` decorator is getting confused when it doesn't see exactly the name of the `@concurrent` function in its own function body. Sadly `@synchronized` is pretty brain dead, all it does is look through its function body for any AST nodes that are `Call`s and checks to see if the target function name matches any `@concurrent` functions.

The trick here is that without some really complicated run time logic, there's not much we can do to determine if any given `Call` is an `@concurrent` function. So sadly, this is probably going to remain as a intended behavior.
