### ISSUE TITLE
cannot pass **kwargs to concurrent? 

### ISSUE THREAD

**Issue by smcveigh-phunware** [alex-sherman/deco#49]
I found this neat library super useful for speeding up (at least 10x from testing)  Pandas [read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html#pandas-read-csv "pandas doc") for reading large files and [concat](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html#pandas-concat "pandas doc")  the resulting data frames.

However, I found when reading in YAML config for passing **kwargs to read_csv, suddenly it doesn't work.

Example:

```python
from typing import List
from pathlib import Path
from pandas import DataFrame, read_csv, concat
from deco import concurrent, synchronized

@concurrent
def read_csv_worker(path: Path, **kwargs) -> DataFrame:
    return read_csv(path, **kwargs)

@synchronized
def read_csv_dispatcher(paths: List[Path], **kwargs) -> DataFrame:
    data = list()
    for p in paths:
        data.append(read_csv_worker(p, **kwargs))
    return concat(data)
```

Fails, but:

```python
from typing import List
from pathlib import Path
from pandas import DataFrame, read_csv, concat
from deco import concurrent, synchronized

@concurrent
def read_csv_worker(path: Path, kwargs) -> DataFrame:
    return read_csv(path, **kwargs)
    
@synchronized
def read_csv_dispatcher(paths: List[Path], **kwargs) -> DataFrame:
    data = list()
    for p in paths:
        data.append(read_csv_worker(p, kwargs))
    return concat(data)
```

works fine.  Do the decorators not support `**kwargs` pass-throughs?

**Comment by alex-sherman** [comment]
What you found is definitely a bug, thanks a bunch for finding this and pointing it out. I was able to fix it in commit b17e6b51ed5dafb4486cfb8e4f9886bb753a24f4 and if you pull that down and install from source you should be able to run this example.

Thanks again, and let me know if the new commit fixes your problem.
