### ISSUE TITLE
Can I specify the number of processes to use manually?

### ISSUE THREAD

**Issue by theRealSuperMario** [alex-sherman/deco#53]
Love the project, saves me a lot of code.
I was just wondering if I can manually specify how many processes I want to allocate.
sorry if the answer is somewhere but I did not find it.

**Comment by alex-sherman** [comment]
Yeah there is, I have a small wiki on this project page that has a bit of [documentation on that](https://github.com/alex-sherman/deco/wiki/@concurrent#custom-parameters). All of the keyword arguments passed to `@concurrent` get passed to the constructor of a `multiprocessing.Pool`. So it's really just:

```python
@concurrent(processes=2)
def work():
    ...
```
