### ISSUE TITLE
Issues With Hanging Processes / Restart

### ISSUE THREAD

**Issue by SoundsSerious** [alex-sherman/deco#58]
Hi,

Really love this idea, this is the way parallel processing should be :)

I'm having an issue where the same code will sometimes work as expected and create many processes, however, sometimes it appears it will get stuck with one process.

Wondering if anyone else is having/has had this issue and if there is a fix.

I've had this issue on osx, windows and through python and ipython qt console.

**Comment by alex-sherman** [comment]
Can you post code that reproduces this problem?

**Comment by SoundsSerious** [comment]
Hey @alex-sherman

Found the issue a while ago, the error has to do with opening matplotlib window with the tk backend, i assume there is some kind of concurrency blocking with tk

I did not have this problem if i switched ipython to the qt backend
