### ISSUE TITLE
Is nbody.py a Deco example? 

### ISSUE THREAD

**Issue by go-dustin** [alex-sherman/deco#59]
Looking through the examples, this script doesn't appear to be Deco related. Am I missing something?

**Comment by alex-sherman** [comment]
That example was originally split into two files, so all the deco related stuff was in simulate.py. I've stuffed it all into one file, but I'm thinking it's kind of a verbose example that doesn't really demonstrate that much.

https://github.com/alex-sherman/deco/commit/ba5059d14cd9c6f63b1fb0b0ae588b428ab11a28#diff-7af4c220cd6b48e22c7cfe2bf39c955c
