### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by avyfain** [alex-sherman/deco#6]
Thanks for publishing this code, I would really like to play with it!
Sadly, without an explicit license, I can't really do so.

"a proper software license is a necessary evil for any code you plan to release to the public (...) Because I did not explicitly indicate a license, I declared an implicit copyright without explaining how others could use my code." [Coding Horror](http://blog.codinghorror.com/pick-a-license-any-license/)

GH has [made this easy](http://choosealicense.com/).

**Comment by alex-sherman** [comment]
Thanks for pointing this out, I've added a license.

**Comment by avyfain** [comment]
Wow, quick response, thanks a lot! :)
