### ISSUE TITLE
User problem: where to look for when passing and receiving complex data structures?

### ISSUE THREAD

**Issue by haimivan** [alex-sherman/deco#62]
Hi,

I recently started using `deco`.

I face the following problem and I am not sure how I can get rid of it:

I have a complex data structure that I pass to  `process_data_set()` function and further on to `process_lat_lon()`. The data I return in `process_lat_lon()` is complex, too (I use here the function names of the deco example `climate_model.py`) . Posting here a minimal reproducible example is already quite an effort.

When using both the decorators, I get the following error:

        raise self.not_implemented_error(node, "Concurrent assignment only implemented for index based objects")

thrown at:

    astutil.py

    class SchedulerRewriter(NodeTransformer):
            ....
            if not type(node.targets[0]) is ast.Subscript:
                raise self.not_implemented_error(node, "Concurrent assignment only implemented for index based objects")

`node` looks like the following in the debugger at that position:

![Screenshot from 2020-10-28 16-15-18](https://user-images.githubusercontent.com/10325765/97456146-deb1f680-1938-11eb-84d9-e342b4915cf7.png)

If I omit the `synchronized` decorator at `process_data_set()`, there is no error and I can find my desired result in the following substructure:

    process_data_set(data)[0].async_result._value[0]

**What do I have to do / where do I have to look for to get my code working also with the `synchronized` decorator?**

Thanks in advance.

**Comment by alex-sherman** [comment]
Based on the AST dump you provided it looks like you're using the `concurrent` method like:

```python
result = concurrentMethod()
```

The error is trying to say that it can only be used like:

```python
results[index] = concurrentMethod()
```

Sadly `deco` is not smart enough to parallelize the first example, and it relies entirely only being able to store individual results back into a list/dict.

Please let me know if I missed something, but closing for now. Thanks for taking a look!

**Comment by haimivan** [comment]
Hi Alex,

your hint was very helpful and solved my issue.

Thanks a lot!
