### ISSUE TITLE
Is it a good idea to pass read-only variables in a global like manner to the @concurrent function?

### ISSUE THREAD

**Issue by haimivan** [alex-sherman/deco#63]
Hi,

I have a very big array that needs to be passed to the `@concurrent` function.

As this might get time consuming (when done a lot of times), I would like to pass it only once.

I can read in the  [documentation](https://github.com/alex-sherman/deco/wiki/Common-Pitfalls)  that global variables should not be used in `@concurrent`.

As the code example below shows, this seems to be also true for global alike variables like singleton members:
In the first call the value of `SingleRunResultKeeper.runInput` is properly processed. The update from `15` to `-100` seems to be ignored in the second call.

As my big array (residing in `SingleRunResultKeeper.runInput`) is read only in my code from a functional point of view:

Can I assume that it is safe to set the value of this variable _before the first call_ of the `@concurrent` and `@synchronized` construct and that this value is processed later-on without any problems?

The code:
```

from deco import *
import time
import random
from collections import defaultdict

class Singleton(type):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]


class SingleRunResultKeeper(metaclass=Singleton):
    pass

    def __init__(self):
        self.runInput = 0


@concurrent  # We add this for the concurrent function
def process_lat_lon(lat, lon, data):
    runInput = SingleRunResultKeeper.runInput

    time.sleep(0.1)
    myReturn = data[lat + lon] + runInput
    return myReturn


@synchronized  # And we add this for the function which calls the concurrent function
def process_data_set(data):
    results = defaultdict(dict)
    for lat in range(5):
        for lon in range(5):
            results[lat][lon] = process_lat_lon(lat, lon, data)
    dictOfResults = dict(results)
    return dictOfResults


if __name__ == "__main__":
    random.seed(0)
    data = [random.random() for _ in range(200)]
    start = time.time()
    SingleRunResultKeeper.runInput = 15
    data_set = process_data_set(data)
    print('first call', data_set)

    SingleRunResultKeeper.runInput = -100
    data_set = process_data_set(data)
    print('second call', data_set)

    print(time.time() - start)
```
result:

```
first call {0: {0: 15.844421851525048, 1: 15.757954402940303, 2: 15.420571580830845, 3: 15.258916750292963, 4: 15.511274721368608}, 1: {0: 15.757954402940303, 1: 15.420571580830845, 2: 15.258916750292963, 3: 15.511274721368608, 4: 15.404934137450415}, 2: {0: 15.420571580830845, 1: 15.258916750292963, 2: 15.511274721368608, 3: 15.404934137450415, 4: 15.783798589034772}, 3: {0: 15.258916750292963, 1: 15.511274721368608, 2: 15.404934137450415, 3: 15.783798589034772, 4: 15.303312726078927}, 4: {0: 15.511274721368608, 1: 15.404934137450415, 2: 15.783798589034772, 3: 15.303312726078927, 4: 15.476596954152356}}
second call {0: {0: 15.844421851525048, 1: 15.757954402940303, 2: 15.420571580830845, 3: 15.258916750292963, 4: 15.511274721368608}, 1: {0: 15.757954402940303, 1: 15.420571580830845, 2: 15.258916750292963, 3: 15.511274721368608, 4: 15.404934137450415}, 2: {0: 15.420571580830845, 1: 15.258916750292963, 2: 15.511274721368608, 3: 15.404934137450415, 4: 15.783798589034772}, 3: {0: 15.258916750292963, 1: 15.511274721368608, 2: 15.404934137450415, 3: 15.783798589034772, 4: 15.303312726078927}, 4: {0: 15.511274721368608, 1: 15.404934137450415, 2: 15.783798589034772, 3: 15.303312726078927, 4: 15.476596954152356}}
1.439558982849121
```

Thanks in advance!

**Comment by alex-sherman** [comment]
Global variables are disallowed because side-effects of `@concurrent` methods are not observable in the main process.

What happens practically is your module gets executed in the main process with `__name__ == "__main__"` and as it's running the `@synchronized` method, all calls to `@concurrent` methods gets passed to _separate processes_ which will also start by executing your module (although this time with `__name__ != "__main__"`. So in those separate processes the value of your singleton will not only _not_ have been set, any changes to it will not be observed in the main process since they happened in a separate process.

I was a bit confused by your example because I figured _neither_ call should reflect the values 15 or -100. When I tried running it I got:

```
Traceback (most recent call last):
  File "C:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python36\lib\site-packages\deco\conc.py", line 10, in concWrapper
    result = concurrent.functions[f](*args, **kwargs)
  File "C:\Code\deco\examples\faff.py", line 24, in process_lat_lon
    runInput = SingleRunResultKeeper.runInput
AttributeError: type object 'SingleRunResultKeeper' has no attribute 'runInput'
```

Which makes sense to me since the child processes should not have executed either assignment of `SingleRunResultKeeper.runInput`

#16 is the feature request to fix this, but not sure I will find time to. One way to work around this would be to move any global variables outside of the `if __name__ == "__main__"` like: 

```python
SingleRunResultKeeper.runInput = 15
if __name__ == "__main__":
    random.seed(0)
    data = [random.random() for _ in range(200)]
    start = time.time()
    data_set = process_data_set(data)
    print('first call', data_set)

    data_set = process_data_set(data)
    print('second call', data_set)

    print(time.time() - start)
```

Of course you can't modify it during the program execution so it must _really_ be read only. Hope that helps! Closing for now, feel free to reopen if I missed something.

**Comment by haimivan** [comment]
Hi Alex,

>Traceback (most recent call last):
>  File "C:\Python36\lib\multiprocessing\pool.py", line 119, in worker
>    result = (True, func(*args, **kwds))
  File "C:\Python36\lib\site-packages\deco\conc.py", line 10, in concWrapper
    result = concurrent.functions[f](*args, **kwargs)
  File "C:\Code\deco\examples\faff.py", line 24, in process_lat_lon
    runInput = SingleRunResultKeeper.runInput
AttributeError: type object 'SingleRunResultKeeper' has no attribute 'runInput'
>

This error seems to be Windows specific. In Ubuntu/Linux it does not occur.

>all calls to @concurrent methods gets passed to separate processes which will also start by executing your module (although this time with __name__ != "__main__"). 

Do I understand it correctly, that if I have 4 cores in my computer, that my module gets started 4 times with `__name__ != "__main__"`?

**Comment by alex-sherman** [comment]
Wow TIL: on Linux the behavior of multiprocessing is [very different from windows](https://www.pythonforthelab.com/blog/differences-between-multiprocessing-windows-and-linux/). On Windows, yes your module will get started N times with `__name__ != "__main__"` but on Linux the child processes are forked when the pool is created, which in `deco` is the first time a `@concurrent` function is encountered. Which means the child processes will reflect any global variable mutations up to that point.

I think I'll double down on the "avoid global variable use" mantra in that case. However, my suggestion to initialize a readonly global variable before the `if __name__ != "__main__"` block will still work as long as the initialization is stable/deterministic.
