### ISSUE TITLE
TypeError: cannot pickle '_nrt_python._MemInfo' object when passing a numba Dict to the @concurrent function

### ISSUE THREAD

**Issue by haimivan** [alex-sherman/deco#69]
Hi,

thanks for creating and maintaining this library!

I have presently the issue that I cannot pass numba Dict objects to the `@concurrent` function.
In the example below, I create a numba Dict that I need in my real code (the function `work()` calls a numba jitted function that I made).

Is there anything I can do by myself about this? Thanks in advance!

Converting a Python dict to a numba Dict in `work()` unfortunately is not an option, as this would lead to a performance degradation (as you can see, adding entries to the numba Dict takes some time... ).

I am using Ubuntu and Python 3.8

the code:

```python
from deco import synchronized
from deco import concurrent
import time
import numba as nb


@concurrent
def work(myInput):
    time.sleep(0.1)


@synchronized
def run(myDict):
    for _ in range(100):
        work(myDict)


if __name__ == "__main__":

    nbFloatDict = nb.typed.Dict.empty(
        key_type=nb.types.unicode_type,
        value_type=nb.types.float64, )
    start = time.time()
    nbFloatDict['a'] = 1.
    print("time.time() - start=", time.time() - start)

    start = time.time()
    run(nbFloatDict)
    print("Executing in serial should take 10 seconds")
    print("Executing in parallel took:", time.time() - start, "seconds")

```

The error:

```python
time.time() - start= 1.769632339477539
Traceback (most recent call last):
  File "/home/user/PycharmProjects/myproject/mytest.py", line 30, in <module>
    run(nbFloatDict)
  File "/home/user/venv/numba38/lib/python3.8/site-packages/deco/conc.py", line 62, in __call__
    return self.f(*args, **kwargs)
  File "<string>", line 2, in run
  File "/home/user/venv/numba38/lib/python3.8/site-packages/deco/conc.py", line 139, in wait
    result, operations = self.results.pop().get()
  File "/home/user/venv/numba38/lib/python3.8/site-packages/deco/conc.py", line 159, in get
    return self.async_result.get(3e+6)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 537, in _handle_tasks
    put(task)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
TypeError: cannot pickle '_nrt_python._MemInfo' object
```

**Comment by alex-sherman** [comment]
In order to run in separate processes the arguments to `@concurrent` functions need to be pickleable. I think that requirement does not exist if you're using threads, but then you'll only get concurrency and not parallelism.

You'll have to find a way to make the arguments (and return values) pickleable, perhaps by passing a handle to the work item, index or something, and then constructing the dictionary inside the `@concurrent` function rather than passing it in. (Or use threads if concurrency is enough).

**Comment by alex-sherman** [comment]
Updated the README to mention this limitation in 17f5c47
