### ISSUE TITLE
Setting and handling timeout

### ISSUE THREAD

**Issue by WindsurfAR** [alex-sherman/deco#71]
Hi!
First, I wanted to thank you for this module, it was extremely useful to me. I needed to parallelize some parts of a tool I made, but did not have any knowledge of asyncio. Then found deco, plugged it in, and voilá! Two decorators and ready to go! Many times faster than before.
Now, I am trying to improve my control over the program flow. In my program I make a lot of API requests, every few seconds. The problem I found is that, if one of them gets timed out, or is much slower than normal, the rest have to wait for it to finish (as expected).
I would like to set a timeout for that, but I still couldn't do it. I tried modifying the wait argument (https://docs.python.org/2/library/multiprocessing.html#multiprocessing.pool.AsyncResult.wait) in https://github.com/alex-sherman/deco/blob/17f5c4765ed43fdfb472676663bc17c16faa85f3/deco/conc.py#L159 but then I get the TimeOut exceptions that aren't being handled, and don't know how to handle.
Sorry if this is a noobish question, still learning a lot about intermediate-advanced python in general.

Thanks in advance!

**Comment by alex-sherman** [comment]
I wouldn't modify the timeout inside `deco`, but set the timeout at the HTTP request layer and handle it. For example (if you're using `requests`) https://docs.python-requests.org/en/latest/user/advanced/#timeouts

**Comment by WindsurfAR** [comment]
Thanks for the fast answer, and yes, I thought that that would be the best solution. But not all of the concurrent actions are plain requests, I didn't clarify that, sorry. For example, some are calls to WSL bash (Windows Subsystem for Linux), and those are the ones I get less control about the requests they make, and the ones that I want to timeout if they take too long.
Thanks again Alex!
